---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shiro-bot-harbor-regcred
  namespace: ibuki-shiro-bot
spec:
  encryptedData:
    .dockerconfigjson: AgB31uBOpCRBtn1llQboAce/eWhDUVGB+pNEGq7iBng/0qbRWNFG80+3S+zpnGx3DtN6sFGuRPz65tL5cd4/Mm3pqEQewqEvk3TXQsOIMdMXXr1XqKaMjPzXXz1lIaMaV3BTj2L2C5dFomhLuzFqPfoVkrirCKGk6G01EcC5FGovOan6M+kdjiHLVvKIYy2mKR+98fILr5CUzf8wfEizbAA4+hvPWKiz9ObxokZsHGUAYG9c4VYb44Om0qJVNQV7j4ghWxUG2OnPNqhoUnKKWqVHo6q91qpwHLRG8By7lkIPOtKzkZN7j3HnjP1HNvVHseGNER0axzPAQK+iiOhxDw5oPMVitEe9Fp7cpLeaR3DaF5q6UBRLGSQLvmelX7y5onwoehSEHcbVosekqXynjJFG+Ics3PYdz/IF7p2V3Fxt0BrGcrwarDtXeRgA2SEmDyZH1pelBsPTOU+ubrktrvkqwtdYqgfiEuIV8m2WLblffMhazSm/u5hRpcpH7DowQnR+XGg8OuPYbj7kM6I0/lgqOiISVgquxPEGKr2MSVpzYW1uSkKIj69auO9EuzERVWSD6itUJlCJHT6Z1bmDJIGtj+d2SK0K2Wx8epyborvzP4yOmgvR6oVgHN4pJUCyxgb+2ZQBw8BZ9oowimGwXlaWGarIoADhWk7lVxBLNXj2qEK6EG1P62rX9QzNatSevmQnV3L3VoXGvN6gdCQUQIFTjDOAUpJC/U//X1UVsAICbXvBUdem1kB4Lq+jBPQcPG+hrBNtgRnB6t8Ah1N0WGPFsi2hzWaionOLct95jkIJfQoCI7wf5eHgQTvveid+sC1vilCPM5RzcB8Bf+7vwJZVnE1xuSAzto/NwEnhJ7LrSjsmypu0JXLdI9QA3VLPk6Z9hfxNEBmDwrwdie6fJKoAuQ==
  template:
    metadata:
      name: shiro-bot-harbor-regcred
      namespace: ibuki-shiro-bot
    type: kubernetes.io/dockerconfigjson
