---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shiro-bot-harbor-regcred
  namespace: ibuki-shiro-bot
spec:
  encryptedData:
    .dockerconfigjson: AgCFx4VASn27H9uRucLBW4eEvuBDQbK3uPnATBsp602e6oSw4BwjzU08BF8nx0cZN55pN3Q3AIJ6VSlnD5rTwxNVpXMArpgaY45BaCHkxcmVGpq2YAcwqFk7rVTr0I2YzPeqeUlVVEyS251IwnYFe1i7CqWxUFHwBM7Kf6efvw9peQkdGnKrtUGLMHiQDP0KUyeTmACwNgUNMAsGljjUaoHYDxaZ62lWwkuRWYW/0LEU4ZVPybxJWdx5ls219aG8F89f3WIlGVqTEzhTciy7Jcrrgy5+Kg1t8uK4ereTsge3FgnJAp4h2eyioywXgr0eGZwASMefAMMhvTQbSdQy3jTjy2IYfiTlkf0MS3CVpUdUIDbuTrqNU59lofrYOy3y5yv2wSxE0neYXbrJbuaTCcHzaR/2uUr/1bs5aAhjlfCBQZKeTUOig+eRuyRJ7wkgD6GHT9Ap3CTe/eHUvrDK4XmYKLqUdA3Ib4XiaK2EPkoFXEm4uTWf9j1MUlylfzLpe8SMqBlWYnd9aDoRGsRTCPHHyLF79zRQjxWe9nEuQKNyF2ewMFu5mZSXCpM7reRL6riLwD7GAbPr0BH4DNnmfKQpHDqZHHDgAy5+30vBx0VD8sTxDMvoFK9T3RZgs56c3KAClvS6cMDxiCZpCfVCH27BFhMAmrQFK6rPWN/I8PIhwKN2kjk6wSXHIHoYnY4zZVgpwNQaZGKIAzP8XOEz50ziWUdaQP/NGGt818wahbJGXP7TO0scvLCKjuhvbXDVes3of3cnE1ToW02NpOltUcu/+ZcohdOXNXlUiptvfWs262Yw9dA6dvC3stHqUrBZePBfFgDlA5Qx9ozIpKR43WLoECu64gRDQ4htQeyn4UsUjOFhmIQXGIJHSueoURc9jpi4blVdsoOHgAyS4Bvc6VXmmssAwl/Gl2g=
  template:
    metadata:
      name: shiro-bot-harbor-regcred
      namespace: ibuki-shiro-bot
    type: kubernetes.io/dockerconfigjson
